apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: beers-back-end-deployment
  labels:
    app: beers-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beers-app
  template:
    metadata:
      labels:
        app: beers-app
    spec:
      containers:
      - name: beers-app
        image: zorag/beer-app-backend:latest
        ports:
        - containerPort: 9000
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: beers-app-service
spec:
  selector:
    app: beers-app
  ports:
  - protocol: TCP
    port: 9876
    targetPort: 9000
  type: LoadBalancer